config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new', as: 'login'
 
  resources :users do
    resources :folders, only: [:new, :create, :index, :show]
  end
  get '/folder/:folder_id/files/new', to: 'user_files#new', as: 'new_file'
  post '/folder/:folder_id/files/create', to: 'user_files#create', as: 'create_file'
  get '/files/:file_id', to: 'user_files#show', as: 'download' 
  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/users/:user_id/folder/:folder_id/files/:id/destroy', to: 'user_files#destroy', as: 'delete_file'
  get '/users/:user_id/folder/:folder_id/destroy', to: 'folders#destroy', as: 'delete_folder'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
    belongs_to :user
    has_many :user_files
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :folders
end

app/models/user_file.rb
class UserFile < ApplicationRecord
    belongs_to :folder
    def uploaded_file=(incoming_file) 
        self.filename = incoming_file.values[0].original_filename 
        self.content_type = incoming_file.values[0].content_type
        self.data = incoming_file.values[0].tempfile
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :require_login
    def current_user
        User.find_by(id: session[:user_id])
    end

    def require_login
        redirect_to login_path, alert: 'Must be Logged in to view this action' if current_user.nil?
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
    before_action :require_login 
    def new
        @user = User.find(params[:user_id])
        @folder = Folder.new
    end

    def index
        @user = User.find(params[:user_id])
        @folders = @user.folders
    end

    def show
        @folder = Folder.find_by(id: params[:id])
        @user = User.find_by(id: params[:user_id])
        @files = @folder.user_files
    end

    def create
        @folder = Folder.create(folder_params)
        @user = User.find_by(id: folder_params[:user_id])
        @user.folders << @folder
        redirect_to user_folder_path(@user, @folder)
    end

    def destroy
        @folder = Folder.find_by(id: params[:folder_id])
        @user = User.find_by(id: params[:user_id])
        @folder.user_files.delete_all
        Folder.delete(@folder)
        redirect_to user_folders_path(@user) 
    end

    private
    def folder_params
        params.require(:folder).permit(:name, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
            redirect_to user_path(@user)
        else
            @user = User.new
        end
    end

    def create
        @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            puts 'I cant find that person'
            redirect_to login_path
        end
    end

    def destroy
        session.delete :user_id
        redirect_to login_path
    end

end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
   before_action :require_login 
   def new 
        @user_file = UserFile.new
        @folder = Folder.find(params[:folder_id])
   end

   def show

        @user_file = UserFile.find(params[:file_id])
        send_data @user_file.data, :filename => @user_file.filename, :type => @user_file.content_type
   end

   def create
        return if params[:user_file].blank?
        @folder = Folder.find(params[:folder_id])
        @user = User.find(session[:user_id])
        @user_file = UserFile.new
        @user_file.uploaded_file = params[:user_file]
        @user_file.folder = @folder
        if @user_file.save
            flash[:notice] = "Thank you for your submission"
            redirect_to user_folder_path(@user, @folder)
        else
            flash[:error] = "There was a problem submitting your attachment."
            redirect_to new_user_file(@user.id)
        end
    end

    def destroy
        @folder = Folder.find(params[:folder_id])
        @user = User.find(session[:user_id])
        @user_file = params[:id]
        UserFile.delete(@user_file)
        redirect_to user_folder_path(@user, @folder)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show] 
    def new
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
            redirect_to user_path(@user)
        else
            @user = User.new
        end
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            puts "Invalid Entry"
            redirect_to new_user_path
        end
    end

    def show
        @user = User.find(params[:id])
    end
        

    private
    def user_params
        params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/folders/index.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to("NEW FOLDER", new_user_folder_path(@user)) %></li>
  <li class='active'><%= link_to("MY FOLDERS", user_folders_path(@user)) %></li>
  <li><%= link_to("HOME", user_path(@user))%></li>
  <li><%=link_to("LOGOUT", logout_path)%>
</ul>
<div class='container'>    
    <h1><%=@user.name%>'s Folders</h1>
    <% @folders.each do |folder| %>
        <h3><%=link_to(folder.name, user_folder_path(@user.id, folder.id))%>   <button type='button' class='btn btn-danger'><%=link_to('DELETE', delete_folder_path(@user,folder))%></button></h3>
    <%end%>
      <img class= 'img-thumbnail' src='https://images.pexels.com/photos/2128249/pexels-photo-2128249.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' alt='filecab'/>
</div>

app/views/folders/new.html.erb
<div class ='container'>
    <div class ='jumbotron'>
        <h2>New Folder</h2>
        <%=form_for @folder, url: "/users/:user_id/folders", method: 'post' do |f|%>
            <div class='form-group'>
            <%=f.label :name, "Folder Name" %>
            <%=f.text_field :name, class: 'form-control'%>
            </div>
            <%= f.hidden_field :user_id, :value => @user.id%>
            <%=f.submit 'Create', class: 'btn-btn-default'%>
        <%end%>
    </div>
    <img class='img-thumbnail' src='https://images.pexels.com/photos/1370294/pexels-photo-1370294.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' alt='filecab'>
</div>

app/views/folders/show.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to("NEW FILE", new_file_path(@folder)) %></li>
  <li><%= link_to("MY FOLDERS", user_folders_path(@user)) %></li>
  <li><%= link_to("HOME", user_path(@user))%></li>
  <li><%=link_to("LOGOUT", logout_path)%>
</ul>
<div class='container'>
    <h1><%= @user.name%>'s FOLDER: <%= @folder.name%></h1>
    <ul><h3>Files</h3>
        <% @files.each do |fl|%>
            <h4> Name: <%=fl.filename%><br/> <%=link_to("DOWNLOAD", download_path(fl))%> <button class='btn btn-danger'><%=link_to('DELETE', delete_file_path(@user,@folder,fl.id))%></button></h4>
        <%end%>
    </ul>
    <img class='img-thumbnail' src='https://images.pexels.com/photos/357514/pexels-photo-357514.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' alt='file'>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FILECLOUD</title>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript --> 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%# <style media="screen">
      body { background: #ECEFF1; color: rgba(0,0,0,0.87); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
      #message { background: white; max-width: 360px; margin: 100px auto 16px; padding: 32px 24px; border-radius: 3px; }
      #message h2 { color: #ffa100; font-weight: bold; font-size: 16px; margin: 0 0 8px; }
      #message h1 { font-size: 22px; font-weight: 300; color: rgba(0,0,0,0.6); margin: 0 0 16px;}
      #message p { line-height: 140%; margin: 16px 0 24px; font-size: 14px; }
      #message a { display: block; text-align: center; background: #039be5; text-transform: uppercase; text-decoration: none; color: white; padding: 16px; border-radius: 4px; }
      #message, #message a { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }
      #load { color: rgba(0,0,0,0.4); text-align: center; font-size: 13px; }
      @media (max-width: 600px) {
        body, #message { margin-top: 0; background: white; box-shadow: none; }
        body { border-top: 16px solid #ffa100; }
      }
    </style> %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/user_files/new.html.erb
<div class = 'container'>
    <div class='jumbotron'>
        <h1>New File</h1>
        <%= form_for @user_file, url: create_file_path(@folder),  :multipart => true do |f| %>
            <div class='form-group'>
            <%= f.file_field 'user_file', class: 'form-control'%>
            </div>
            <%= f.hidden_field :folder_id, :value => @folder.id%>
            <%= f.submit "Send File", class: "btn btn-default"%>
        <%end%>
    </div>
    <img class='img-thumbnail' src='https://images.pexels.com/photos/1370294/pexels-photo-1370294.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' alt='filecab'>
</div>

app/views/users/new.html.erb
<ul class="nav nav-tabs">
  <li class="active"><%= link_to('Signup', new_user_path)%></li>
  <li><%= link_to('Sign in', login_path)%></li>
</ul>

<div class='container'>
    
    <div class='jumbotron'>
        <h1>FILECLOUD</h1>
        <img class='img-thumbnail' src='https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' alt='cloudCity'>
        
        <h3>Sign up</h3>
        <%=form_for @user do |f|%>
            <div class='form-group'>
                <%=f.label :name, "Enter Your Name"%>
                <%=f.text_field :name, class: 'form-control'%>
            </div>
            <div class='form-group'>
                <%=f.label :password, "Enter Your Password"%>
                <%=f.text_field :password, class: 'form-control' %>
            </div>
            <%=f.submit 'Create User', class: "btn btn-default"%>
        <%end%>
        
    </div>
</div>

app/views/users/show.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to("NEW FOLDER", new_user_folder_path(@user)) %></li>
  <li><%= link_to("MY FOLDERS", user_folders_path(@user)) %></li>
  <li class='active'><%= link_to("HOME", user_path(@user))%></li>
  <li><%=link_to("LOGOUT", logout_path)%>
</ul>
<div class='jumbotron'>
  <h1>User: <%= @user.name%></h1>
  <img class="img-thumbnail" src="https://images.pexels.com/photos/207489/pexels-photo-207489.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="cloudimg">
</div>